name: Release
on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          tag_format: '${version}'
          working_directory: .github
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              {
                name: 'develop',
                prerelease: true
              }
            ]            
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
