name: Release
on:
  push:
    branches:
      - main
      - develop
      - release/*
      - hotfix/*            
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.base_ref == 'develop' && !startsWith(github.head_ref, 'release/'))
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          tag_format: '${version}'
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git
          branches: |
            [
              'main',
              'hotfix/*',
              {
                name: 'develop',
                prerelease: 'beta'
              },
              {
                name: 'release/*',
                prerelease: 'rc'
              }
            ]            
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
